openapi: 3.0.0
info:
  title: APIs OpenData do Open Insurance Brasil
  description: As APIs descritas neste documento são referentes as APIs da fase OpenData do Open Insurance Brasil.
  version: 0.0.1
  contact:
    url: 'https://openinsurance.susep.gov.br'
tags:
  - name: "Channels"
    description: "Operações para listagem de canais de atendimentos"
servers:
  - url: http://api.sociedade.com.br/open-insurance/channels/v1
paths:
  /branches:
    get:
      tags:
        - "Channels"
      summary: Obtém a lista de dependências próprias da sociedade supervisionada.
      description: "Método para obter a lista de dependências próprias da sociedade supervisionada."
      operationId: "getBranches"
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pageSize"
      responses:
        '200':
          description: Lista de dependências próprias obtida com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBranchesList'
  /electronic-channels:
    get:
      tags:
        - "Channels"
      summary: Obtém a lista de canais eletrônicos de atendimento da sociedade supervisionada.
      description: "Método para obter a lista de canais eletrônicos de atendimento da sociedade supervisionada."
      operationId: "getElectronicChannels"
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pageSize"
      responses:
        '200':
          description: Lista de canais eletrônicos de atendimento obtida com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseElectronicChannelsList'
  /phone-channels:
    get:
      tags:
        - "Channels"
      summary: "Obtém a lista de canais telefônicos de atendimento da sociedade supervisionada."
      description: "Método para obter a lista de canais telefônicos de atendimento da sociedade supervisionada."
      operationId: "getPhoneChannels"
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pageSize"
      responses:
        '200':
          description: Lista de canais telefônicos de atendimento obtida com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsePhoneChannelsList'
components:
  schemas:
    ResponseBranchesList:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: object
          required:
            - brand
          properties:
            brand:
              $ref: '#/components/schemas/BranchesBrand'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          brand:
            name: Organização A
            companies:
              - name: Empresa A1
                cnpjNumber: '45086338000178'
                urlComplementaryList: 'https://empresaa1.com/branches-insurance'
                branches:
                  - identification:
                      name: 'Marília'
                      openingDate: '2010-01-02'
                    postalAddress:
                      address: 'Av Naburo Ykesaki, 1270'
                      additionalInfo: 'Loja B'
                      districtName: 'Centro'
                      townName: 'Marília'
                      ibgeCode: '3550308'
                      countrySubDivision: 'SP'
                      postCode: '17500-001'
                      country: 'Brasil'
                      countryCode: 'BRA'
                      geographicCoordinates:
                        latitude: "-90.8365180"
                        longitude: "-180.836519"
                    availability:
                      standards:
                        - weekday: SEGUNDA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: TERCA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUARTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUINTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: SEXTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                      exception: 'Exceto feriados municipais, estaduais e nacionais'
                      isPublicAccessAllowed: true
                    phones:
                      - type: FIXO
                        countryCallingCode: '55'
                        areaCode: '14'
                        number: '35721199'
                      - type: MOVEL
                        countryCallingCode: '55'
                        areaCode: '14'
                        number: '997865532'
                    services:
                      - name: "AVISO_DE_SINISTRO"
                        code: "AVISO_DE_SINISTRO"
                      - name: "ENVIO_DE_DOCUMENTOS"
                        code: "ENVIO_DE_DOCUMENTOS"
                        additionalInfo: "Renegociação"
        links:
          self: 'https://api.sociedade.com.br/open-insurance/channels/v1/branches'
          first: 'https://api.sociedade.com.br/open-insurance/channels/v1/branches'
          prev: "null"
          next: "null"
          last: 'https://api.sociedade.com.br/open-insurance/channels/v1/branches'
        meta:
          totalRecords: 1
          totalPages: 1
    BranchesBrand:
      type: object
      required:
        - name
        - companies
      allOf:
        - $ref: '#/components/schemas/Brand'
      properties:
        name:
          type: string
          description: Nome da Marca reportada pelo participante do Open Insurance. O conceito a que se refere a 'marca' é em essência uma promessa da empresa em fornecer uma série específica de atributos, benefícios e serviços uniformes aos clientes.
          maxLength: 80
          pattern: \w*\W*
        companies:
          type: array
          items:
            $ref: '#/components/schemas/BranchesCompany'
          minItems: 1
          description: Companies traz uma lista de todas as instuituições da Marca.
    BranchesCompany:
      type: object
      required:
        - name
        - cnpjNumber
      properties:
        name:
          type: string
          maxLength: 80
          pattern: \w*\W*
        cnpjNumber:
          type: string
          minLength: 14
          maxLength: 14
          pattern: '^(\d{14})$|^NA$'
          description: |
            Número completo do CNPJ da instituição responsável pela dependência - o CNPJ corresponde ao número de inscrição no Cadastro de Pessoa Jurídica.
            Deve-se ter apenas os números do CNPJ, sem máscara
          example: '45086338000178'
        urlComplementaryList:
          type: string
          maxLength: 1024
          pattern: \w*\W*
          example: 'https://example.com/mobile-insurance'
        branches:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
          minItems: 1
          description: Lista de Dependências de uma Instituição
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    ResponseElectronicChannelsList:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: object
          required:
            - brand
          properties:
            brand:
              $ref: '#/components/schemas/ElectronicChannelsBrand'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          brand:
            name: 'Organização A'
            companies:
              - name: 'Empresa A1'
                cnpjNumber: '45086338000178'
                urlComplementaryList: 'https://empresaa1.com/branches-insurance'
                electronicChannels:
                  - identification:
                      type: 'INTERNET'
                      additionalInfo: 'NA'
                      urls:
                        - 'https://empresaa1.com/internet-insurance'
                    services:
                      - name: "ENDOSSO"
                        code: "ENDOSSO"
                        additionalInfo: 'NA'
                      - name: "ALTERACOES_NA_FORMA_DE_PAGAMENTO"
                        code: "ALTERA_FORMA_DE_PAGAMENTO"
                        additionalInfo: 'NA'
        links:
          self: 'https://api.sociedade.com.br/open-insurance/channels/v1/electronic-channels'
          first: 'https://api.sociedade.com.br/open-insurance/channels/v1/electronic-channels'
          prev: "null"
          next: "null"
          last: 'https://api.sociedade.com.br/open-insurance/channels/v1/electronic-channels'
        meta:
          totalRecords: 1
          totalPages: 1
    ElectronicChannelsBrand:
      type: object
      required:
        - name
        - companies
      allOf:
        - $ref: '#/components/schemas/Brand'
      properties:
        name:
          type: string
          description: Nome da marca selecionada pela Organização proprietária da dependência (titular).
          example: "Marca A"
          maxLength: 80
          pattern: \w*\W*
        companies:
          type: array
          items:
            $ref: '#/components/schemas/ElectronicChannelsCompanies'
          minItems: 1
          description: Lista de instituições pertencentes à marca
    ElectronicChannelsCompanies:
      type: object
      required:
        - name
        - electronicChannels
        - cnpjNumber
      properties:
        name:
          type: string
          description: Nome da marca selecionada pela Organização proprietária da dependência (titular).
          example: "Empresa da Marca A"
          maxLength: 80
          pattern: \w*\W*
        urlComplementaryList:
          type: string
          maxLength: 1024
          pattern: \w*\W*
          example: "https://example.com/mobile-insurance"
        electronicChannels:
          type: array
          items:
            $ref: '#/components/schemas/ElectronicChannel'
          minItems: 1
          maxItems: 4
          description: Lista  de canais de atendimento eltrônico
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    Branch:
      type: object
      description: Dependência de sociedades supervisionadas e demais instituições, autorizadas a funcionar pelo Superintendência de Seguros Privados do Brasil, destinada à prática das atividades para as quais a instituição esteja regularmente habilitada.
      required:
        - identification
        - postalAddress
        - availability
        - services
      properties:
        identification:
          $ref: '#/components/schemas/BranchIdentification'
        postalAddresses:
          $ref: '#/components/schemas/BranchPostalAddress'
        availability:
          $ref: '#/components/schemas/BranchAvailability'
        phones:
          type: array
          items:
            $ref: '#/components/schemas/BranchPhone'
          minItems: 1
          description: Lista de telefones da Dependência
        services:
          type: array
          description: Traz a relação de serviços disponbilizados pelo Canal de Atendimento
          items:
            $ref: '#/components/schemas/BranchService'
          minItems: 1
          maxItems: 20
    BranchPostalAddress:
      type: object
      required:
        - address
        - districtName
        - townName
        - countrySubDivision
        - postCode
      allOf:
        - $ref: '#/components/schemas/PostalAddress'
    BranchPhone:
      type: object
      required:
        - type
      allOf:
        - $ref: '#/components/schemas/Phone'
    BranchIdentification:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
          pattern: \w*\W*
          description: Nome da dependência
        openingDate:
          type: string
          maxLength: 10
          pattern: ^(\d{4})-(1[0-2]|0?[1-9])-(3[01]|[12][0-9]|0?[1-9])$
          description: Data de abertura da dependência (uma string com data conforme especificação RFC-3339. p.ex. 2014-03-19)
      required:
        - name
    BranchAvailability:
      type: object
      properties:
        standards:
          type: array
          description: Lista disponibilidade padrão da depêndencia por dias da semana
          items:
            properties:
              weekday:
                type: string
                enum:
                  - DOMINGO
                  - SEGUNDA_FEIRA
                  - TERCA_FEIRA
                  - QUARTA_FEIRA
                  - QUINTA_FEIRA
                  - SEXTA_FEIRA
                  - SABADO
                description: Dia da semana de abertura da dependência
              openingTime:
                type: string
                description: Horário de abertura da dependência (UTC)
                maxLength: 13
                pattern: ^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)|Z$|^NA$
              closingTime:
                type: string
                description: Horário de fechamento da dependência (UTC)
                maxLength: 13
                pattern: ^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)|Z$|^NA$
            required:
              - weekday
              - openingTime
              - closingTime
          minItems: 1
          maxItems: 7
        exception:
          type: string
          maxLength: 2000
          pattern: \w*\W*
          description: Em campo texto devem ser registradas todas as Exceções para o não atendimento.
        isPublicAccessAllowed:
          type: boolean
          description: Indica se a instalação da Dependência tem acesso restrito a clientes.
      required:
        - standards
        - exception
    BranchService:
      type: object
      properties:
        name:
          type: string
          enum:
            - ALTERACOES_NA_FORMA_DE_PAGAMENTO
            - AVISO_DE_SINISTRO
            - CANCELAMENTO
            - EFETIVACAO_DE_APORTE
            - ENDOSSO
            - ENVIO_DE_DOCUMENTOS
            - INFORMACOES_GERAIS_DUVIDAS
            - INFORMACOES_SOBRE_INTERMEDIARIOS
            - INFORMACOES_SOBRE_SERVICOS_DE_ASSISTENCIAS
            - INFORMACOES_SOBRE_SORTEIOS_CAPITALIZACAO
            - PORTABILIDADE
            - RECLAMACAO
            - RESGATE
            - SEGUNDA_VIA_DE_DOCUMENTOS_CONTRATUAIS
            - SUGESTOES_E_ELOGIOS
          description: Nome dos Serviços efetivamente prestados pelo Canal de Atendimento
        code:
          type: string
          enum:
            - ALTERA_FORMA_DE_PAGAMENTO
            - AVISO_DE_SINISTRO
            - CANCELAMENTO
            - EFETIVA_APORTE
            - ENDOSSO
            - ENVIO_DE_DOCUMENTOS
            - INFORMACOES_GERAIS_DUVIDAS
            - INFORMACOES_SOBRE_INTERMEDIARIOS
            - INFORMACOES_SOBRE_SERVICOS_DE_ASSISTENCIAS
            - INFORMACOES_SOBRE_SORTEIOS_CAPITALIZACAO
            - PORTABILIDADE
            - RECLAMACAO
            - RESGATE
            - SEGUNDA_VIA_DE_DOCUMENTOS_CONTRATUAIS
            - SUGESTOES_E_ELOGIOS
          description: Código dos Serviços efetivamente prestados pelo Canal de Atendimento
        additionalInfo:
          type: string
          description: Texto livre para complementar informação relativa ao Serviço disponível, quando for selecionada a opção 'OUTROS_PRODUTOS_SERVICOS'
          maxLength: 2000
          pattern: \w*\W*
      required:
        - code
        - name
    ElectronicChannel:
      type: object
      properties:
        identification:
          $ref: '#/components/schemas/ElectronicChannelIdentification'
        services:
          type: array
          items:
            $ref: '#/components/schemas/ElectronicChannelService'
          minItems: 1
          maxItems: 20
          description: "Traz a relação de serviços disponbilizados pelo Canal de Atendimento"
      required:
        - identification
        - services
    ElectronicChannelIdentification:
      type: object
      required:
        - type
        - urls
      properties:
        type:
          type: string
          enum:
            - INTERNET
            - MOBILE
            - SAC
            - OUVIDORIA
            - CHAT
            - OUTROS
          description: "Tipo de canal de atendimento eletrônico"
          example: "CHAT"
        additionalInfo:
          type: string
          pattern: \w*\W*
          maxLength: 300
          description: |
            Campo de texto livre para descrever complementação de informações necessárias. De preenchimento obrigatório para  o tipo de canal de atendimento 'OUTROS'
            Restrição: Preenchimento obrigatório para o tipo de canal de atendimento 'OUTROS'
        urls:
          type: array
          items:
            $ref: '#/components/schemas/ElectronicChannelUrl'
          minItems: 1
          description: Lista das URLs que atendem um tipo de canal eletrônico selecionado
    ElectronicChannelUrl:
      type: string
      pattern: \w*\W*
      maxLength: 1024
    ElectronicChannelService:
      type: object
      required:
        - name
        - code
      properties:
        name:
          type: string
          enum:
            - ALTERACOES_NA_FORMA_DE_PAGAMENTO
            - AVISO_DE_SINISTRO
            - CANCELAMENTO
            - EFETIVACAO_DE_APORTE
            - ENDOSSO
            - ENVIO_DE_DOCUMENTOS
            - INFORMACOES_GERAIS_DUVIDAS
            - INFORMACOES_SOBRE_INTERMEDIARIOS
            - INFORMACOES_SOBRE_SERVICOS_DE_ASSISTENCIAS
            - INFORMACOES_SOBRE_SORTEIOS_CAPITALIZACAO
            - PORTABILIDADE
            - RECLAMACAO
            - RESGATE
            - SEGUNDA_VIA_DE_DOCUMENTOS_CONTRATUAIS
            - SUGESTOES_E_ELOGIOS
          description: "Nome dos Serviços efetivamente prestados pelo Canal de Atendimento"
          example: "ALTERACOES_NA_FORMA_DE_PAGAMENTO"
        code:
          type: string
          enum:
            - ALTERA_FORMA_DE_PAGAMENTO
            - AVISO_DE_SINISTRO
            - CANCELAMENTO
            - EFETIVA_APORTE
            - ENDOSSO
            - ENVIO_DE_DOCUMENTOS
            - INFORMACOES_GERAIS_DUVIDAS
            - INFORMACOES_SOBRE_INTERMEDIARIOS
            - INFORMACOES_SOBRE_SERVICOS_DE_ASSISTENCIAS
            - INFORMACOES_SOBRE_SORTEIOS_CAPITALIZACAO
            - PORTABILIDADE
            - RECLAMACAO
            - RESGATE
            - SEGUNDA_VIA_DE_DOCUMENTOS_CONTRATUAIS
            - SUGESTOES_E_ELOGIOS
          description: "Código dos Serviços efetivamente prestados pelo Canal de Atendimento"
          example: "ALTERA_FORMA_DE_PAGAMENTO"
        additionalInfo:
          type: string
          maxLength: 2000
          pattern: \w*\W*
          description: "Texto livre para complementar informação relativa ao Serviço disponível, quando for selecionada a opção 'OUTROS_PRODUTOS_SERVICOS'"
          example: "SIC"
    Phone:
      type: object
      properties:
        type:
          type: string
          enum:
            - FIXO
            - MOVEL
          example: "FIXO"
          description: "Identificação do Tipo de telefone da dependência. p.ex.FIXO, MOVEL."
        countryCallingCode:
          type: string
          maxLength: 4
          pattern: ^\d{1,4}$
          example: "55"
          description: "Número de DDI (Discagem Direta Internacional) para  telefone de acesso ao Canal - se houver. p.ex. '55'"
        areaCode:
          type: string
          maxLength: 2
          pattern: ^\d{2}$
          example: "19"
          description: "Número de DDD (Discagem Direta à Distância) do telefone da dependência - se houver. p.ex. '19'"
        number:
          type: string
          maxLength: 11
          pattern: '^([0-9]{8,11})$'
          example: "35721199"
          description: "Número de telefone da dependência - se houver"
    PostalAddress:
      type: object
      properties:
        address:
          type: string
          description: "Deverá trazer toda a informação referente ao endereço da dependência informada: Tipo de logradouro + Nome do logradouro + Número do Logradouro (se não existir usar ' s/n') + complemento (se houver), como, p.ex.: 'R Diamatina, 59, bloco 35, fundos' 'Praça da Boa Vontade s/n'"
          maxLength: 150
          pattern: \w*\W*
          example: 'Av Naburo Ykesaki, 1270'
        additionalInfo:
          type: string
          description: "Alguns logradouros ainda necessitam ser especificados por meio de complemento"
          maxLength: 30
          pattern: \w*\W*
          example: 'Fundos'
        districtName:
          type: string
          description: "Bairro é uma comunidade ou região localizada em uma cidade ou município de acordo com as suas subdivisões geográficas. p.ex: 'Paraíso'"
          maxLength: 50
          pattern: \w*\W*
          example: 'Centro'
        townName:
          type: string
          description: "Localidade: O nome da localidade corresponde à designação da cidade ou município no qual o endereço está localizado. p.ex. 'São Paulo'"
          maxLength: 50
          pattern: \w*\W*
          example: 'Marília'
        ibgeCode:
          type: string
          description: "Código IBGE do município"
          maxLength: 7
          pattern: ^\d{7}$
          example: '3515890'
        countrySubDivision:
          type: string
          description: "Enumeração referente a cada sigla da unidade da federação que identifica o estado ou o distrito federal, no qual o endereço está localizado. p.ex. 'AC'. São consideradas apenas as siglas para os estados brasileiros"
          enum:
            - AC
            - AL
            - AP
            - AM
            - BA
            - CE
            - DF
            - ES
            - GO
            - MA
            - MT
            - MS
            - MG
            - PA
            - PB
            - PR
            - PE
            - PI
            - RJ
            - RN
            - RS
            - RO
            - RR
            - SC
            - SP
            - SE
            - TO
          example: 'SP'
        postCode:
          type: string
          description: "Código de Endereçamento Postal"
          pattern: (\d{8}|^NA$)
          maxLength: 8
          example: '17500001'
        country:
          type: string
          description: "Nome do país"
          maxLength: 80
          pattern: \w*\W*
          example: 'Brasil'
        countryCode:
          type: string
          description: "Código do país"
          example: 'BRA'
        geographicCoordinates:
          $ref: '#/components/schemas/GeographicCoordinates'
    ResponsePhoneChannelsList:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: object
          required:
            - brand
          properties:
            brand:
              $ref: '#/components/schemas/PhoneChannelsBrand'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          brand:
            name: 'Organização A'
            companies:
              - name: 'Empresa A1'
                cnpjNumber: '45086338000178'
                urlComplementaryList: 'https://empresaa1.com/branches-insurance'
                phoneChannels:
                  - identification:
                      type: 'CENTRAL_TELEFONICA'
                      phones:
                        - countryCallingCode: '55'
                          areaCode: '14'
                          number: '35721199'
                          additionalInfo: 'NA'
                        - countryCallingCode: '55'
                          areaCode: '14'
                          number: '997865532'
                          additionalInfo: 'NA'
                    availability:
                      standards:
                        - weekday: SEGUNDA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: TERCA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUARTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUINTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: SEXTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                      exception: 'Exceto feriados municipais, estaduais e nacionais'
                    services:
                      - name: 'INFORMACOES_SOBRE_SERVICOS_DE_ASSISTENCIAS'
                        code: 'INFORMACOES_SOBRE_SERVICOS_DE_ASSISTENCIAS'
                      - name: 'AVISO_DE_SINISTRO'
                        code: 'AVISO_DE_SINISTRO'
                      - name: 'INFORMACOES_SOBRE_SORTEIOS_CAPITALIZACAO'
                        code: 'INFORMACOES_SOBRE_SORTEIOS_CAPITALIZACAO'
                        additionalInfo: "Atendimento em outros idiomas"
                  - identification:
                      type: 'SAC'
                      phones:
                        - countryCallingCode: '55'
                          areaCode: '14'
                          number: '40044828'
                          additionalInfo: 'DDI ''55''; DDD ''11'', 40044828, ''Para clientes no exterior'''
                        - countryCallingCode: '55'
                          areaCode: '14'
                          number: '40044828'
                          additionalInfo: 'DDI '' '', DDD '' '', 40044828, ''Para regiões metropolitanas'''
                        - countryCallingCode: '55'
                          areaCode: '14'
                          number: '40044828'
                          additionalInfo: 'DDI '' '', DDD '' '', 40044828, ''Para demais localidades'''
                    availability:
                      standards:
                        - weekday: SEGUNDA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: TERCA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUARTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUINTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: SEXTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                      exception: 'Exceto feriados municipais, estaduais e nacionais'
                    services:
                      - name: 'INFORMACOES_GERAIS_DUVIDAS'
                        code: 'INFORMACOES_GERAIS_DUVIDAS'
                      - name: 'RECLAMACAO'
                        code: 'RECLAMACAO'
                      - name: 'CANCELAMENTO'
                        code: 'CANCELAMENTO'
                  - identification:
                      type: 'OUVIDORIA'
                      phones:
                        - countryCallingCode: '55'
                          areaCode: '14'
                          number: '40045555'
                          additionalInfo: 'DDI ''55''; DDD ''11'', 40045555, ''Para clientes no exterior'''
                        - countryCallingCode: '55'
                          areaCode: '14'
                          number: '40045555'
                          additionalInfo: 'DDI '' '', DDD '' '', 40045555, ''Para regiões metropolitanas'''
                        - countryCallingCode: '55'
                          areaCode: '14'
                          number: '40045555'
                          additionalInfo: 'DDI '' '', DDD '' '', 40045555, ''Para demais localidades'''
                    availability:
                      standards:
                        - weekday: SEGUNDA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: TERCA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUARTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUINTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: SEXTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                      exception: 'Exceto feriados municipais, estaduais e nacionais'
                    services:
                      - name: 'RECLAMACOES'
                        code: 'RECLAMACOES'
                      - name: 'INFORMACOES_GERAIS_DUVIDAS'
                        code: 'INFORMACOES_GERAIS_DUVIDAS'
                  - identification:
                      type: 'OUTROS'
                      additionalInfo: 'Receptivo'
                      phones:
                        - countryCallingCode: '55'
                          areaCode: 'NA'
                          number: '40043277'
                          additionalInfo: 'DDI ''55''; DDD ''11'', 40043277, ''Para clientes no metropolitanas'''
                        - countryCallingCode: 'NA'
                          areaCode: 'NA'
                          number: '40043277'
                          additionalInfo: 'DDI '' '', DDD '' '', 40043277, ''Para regiões localidades'''
                    availability:
                      standards:
                        - weekday: SEGUNDA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: TERCA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUARTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUINTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: SEXTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                      exception: 'Exceto feriados municipais, estaduais e nacionais'
                    services:
                      - name: 'OUTROS_PRODUTOS_SERVICOS'
                        code: 'OUTROS_PRODUTOS_SERVICOS'
                        additionalInfo: 'Previdência Privada'
        links:
          self: 'https://api.sociedade.com.br/open-insurance/channels/v1/phone-channels'
          first: 'https://api.sociedade.com.br/open-insurance/channels/v1/phone-channels'
          prev: "null"
          next: "null"
          last: 'https://api.sociedade.com.br/open-insurance/channels/v1/phone-channels'
        meta:
          totalRecords: 1
          totalPages: 1
    PhoneChannelsBrand:
      type: object
      required:
        - name
        - companies
      allOf:
        - $ref: '#/components/schemas/Brand'
      properties:
        name:
          type: string
          pattern: '\w*\W*'
          maxLength: 80
          description: "Nome da Marca reportada pelo participante do Open Insurance. O conceito a que se refere a 'marca' utilizada está em definição pelos participantes."
          example: "Marca A"
        companies:
          type: array
          items:
            $ref: '#/components/schemas/PhoneChannelsCompany'
          minItems: 1
          description: Lista de instituições pertencentes à marca
    PhoneChannelsCompany:
      type: object
      required:
        - name
        - phoneChannels
        - cnpjNumber
      properties:
        name:
          type: string
          pattern: \w*\W*
          maxLength: 80
          description: "Nome da Instituição, pertencente à organização, responsável pelo Canal Telefônico."
          example: "Empresa da Marca A"
        urlComplementaryList:
          type: string
          pattern: \w*\W*
          maxLength: 1024
          example: "https://example.com/mobile-insurance"
        phoneChannels:
          type: array
          items:
            $ref: '#/components/schemas/PhoneChannel'
          minItems: 1
          description: Lista  de canais de atendimento telefônico
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    PhoneChannel:
      type: object
      properties:
        identification:
          $ref: '#/components/schemas/PhoneChannelIdentification'
        availability:
          $ref: '#/components/schemas/PhoneChannelAvailability'
        services:
          type: array
          items:
            $ref: '#/components/schemas/PhoneChannelService'
          minItems: 1
          maxItems: 20
          description: Traz a relação de serviços disponbilizados pelo Canal de Atendimento
      required:
        - identification
        - availability
        - services
    PhoneChannelIdentification:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - CENTRAL_TELEFONICA
            - SAC
            - OUVIDORIA
            - OUTROS
          description: "
            Tipo de canal telefônico de atendimento:
              \n* `CENTRAL_TELEFONICA`
              \n* `SAC`
              \n* `OUVIDORIA`
              \n* `OUTROS`"
          example: "OUVIDORIA"
        additionalInfo:
          type: string
          pattern: \w*\W*
          maxLength: 300
          description: Campo de texto livre para descrever informações complementateres sobre canais telefônicos. De preenchimento obrigatório quando o tipo de canal de atendimento telefônico selecionado for "OUTROS"
        phones:
          type: array
          items:
            $ref: '#/components/schemas/PhoneChannelPhone'
          minItems: 1
          description: "Lista de telefones do Canal de Atendimento"
    PhoneChannelAvailability:
      type: object
      properties:
        standards:
          type: array
          description: Lista disponibilidade padrão do canal telefônico por dias da semana
          items:
            properties:
              weekday:
                type: string
                enum:
                  - DOMINGO
                  - SEGUNDA_FEIRA
                  - TERCA_FEIRA
                  - QUARTA_FEIRA
                  - QUINTA_FEIRA
                  - SEXTA_FEIRA
                  - SABADO
                description: Dia da semana de abertura do canal telefônico
              openingTime:
                type: string
                description: Horário de abertura do canal telefônico (UTC)
                maxLength: 13
                pattern: ^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)|Z$|^NA$
              closingTime:
                type: string
                description: Horário de fechamento do canal telefônico (UTC)
                maxLength: 13
                pattern: ^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)|Z$|^NA$
            required:
              - weekday
              - openingTime
              - closingTime
          minItems: 1
          maxItems: 7
        exception:
          type: string
          maxLength: 2000
          pattern: \w*\W*
          description: Em campo texto devem ser registradas todas as Exceções para o não atendimento.
      required:
        - standards
        - exception
    PhoneChannelPhone:
      type: object
      required:
        - countryCallingCode
        - areaCode
        - number
      properties:
        countryCallingCode:
          type: string
          maxLength: 4
          pattern: ^\d{1,4}$|^NA$
          example: "55"
          description: "Número de DDI (Discagem Direta Internacional) para telefone de acesso ao Canal - se houver."
        areaCode:
          type: string
          maxLength: 2
          pattern: ^\d{2}$|^NA$
          example: "19"
          description: "Número de DDD (Discagem Direta à Distância) para telefone de acesso ao Canal - se houver."
        number:
          type: string
          maxLength: 13
          pattern: ^([0-9]{8,11})$|^NA$
          example: "08007787788"
          description: "Número de telefone de acesso ao canal."
        additionalInfo:
          type: string
          maxLength: 300
          pattern: \w*\W*
          example: "Mensagem complementar necessária para o agrupamento da identificação do telefone."
    PhoneChannelService:
      type: object
      required:
        - name
        - code
      properties:
        name:
          type: string
          enum:
            - ALTERACOES_NA_FORMA_DE_PAGAMENTO
            - AVISO_DE_SINISTRO
            - CANCELAMENTO
            - EFETIVACAO_DE_APORTE
            - ENDOSSO
            - ENVIO_DE_DOCUMENTOS
            - INFORMACOES_GERAIS_DUVIDAS
            - INFORMACOES_SOBRE_INTERMEDIARIOS
            - INFORMACOES_SOBRE_SERVICOS_DE_ASSISTENCIAS
            - INFORMACOES_SOBRE_SORTEIOS_CAPITALIZACAO
            - PORTABILIDADE
            - RECLAMACAO
            - RESGATE
            - SEGUNDA_VIA_DE_DOCUMENTOS_CONTRATUAIS
            - SUGESTOES_E_ELOGIOS
          description: "Nome dos Serviços efetivamente prestados pelo Canal de Atendimento"
        code:
          type: string
          enum:
            - ALTERA_FORMA_DE_PAGAMENTO
            - AVISO_DE_SINISTRO
            - CANCELAMENTO
            - EFETIVA_APORTE
            - ENDOSSO
            - ENVIO_DE_DOCUMENTOS
            - INFORMACOES_GERAIS_DUVIDAS
            - INFORMACOES_SOBRE_INTERMEDIARIOS
            - INFORMACOES_SOBRE_SERVICOS_DE_ASSISTENCIAS
            - INFORMACOES_SOBRE_SORTEIOS_CAPITALIZACAO
            - PORTABILIDADE
            - RECLAMACAO
            - RESGATE
            - SEGUNDA_VIA_DE_DOCUMENTOS_CONTRATUAIS
            - SUGESTOES_E_ELOGIOS
          description: "Código dos Serviços efetivamente prestados pelo Canal de Atendimento"
        additionalInfo:
          type: string
          pattern: \w*\W*
          maxLength: 2000
          description: "Texto livre para complementar informação relativa ao Serviço disponível, quando for selecionada a opção 'OUTROS_PRODUTOS_SERVICOS'"
          example: ""
    GeographicCoordinates:
      type: object
      description: Informação referente a geolocalização informada.
      properties:
        latitude:
          description: Informação da latitude referente a geolocalização informada.
          type: string
          pattern: ^-?\d{1,2}\.\d{1,9}$
          maxLength: 13
          example: '-90.8365180'
        longitude:
          description: Informação da longitude referente a geolocalização informada.
          type: string
          pattern: ^-?\d{1,3}\.\d{1,8}$
          maxLength: 13
          example: '-180.836519'
    Brand:
      type: object
      properties:
        name:
          type: string
          maxLength: 80
          pattern: \w*\W*
          description: Nome da marca selecionada pela Organização
          example: Organização A
    CNPJ:
      type: object
      properties:
        cnpjNumber:
          type: string
          pattern: '^(\d{14})$|^NA$'
          description: Número completo do CNPJ da instituição
          maxLength: 14
          example: "50685362000135"
    Links:
      type: object
      properties:
        self:
          type: string
          description: URL da página atualmente requisitada
          example: "https://api.sociedade.com.br/open-insurance/channels/v1/<resource>"
        first:
          type: string
          description: URL da primeira página de registros
          example: "https://api.sociedade.com.br/open-insurance/channels/v1/<resource>"
        prev:
          type: string
          description: URL da página anterior de registros
        next:
          type: string
          description: URL da próxima página de registros
        last:
          type: string
          description: URL da última página de registros
          example: "https://api.sociedade.com.br/open-insurance/channels/v1/<resource>"
    Meta:
      type: object
      properties:
        totalRecords:
          type: integer
          description: Total de registros encontrados
          example: 1
        totalPages:
          type: integer
          description: Total de páginas para os registros encontrados
          example: 1
      required:
        - totalRecords
        - totalPages
  parameters:
    page:
      name: page
      in: query
      description: Número da página que está sendo requisitada (o valor da primeira página é 1).
      schema:
        type: integer
        default: 1
        minimum: 1
    pageSize:
      name: page-size
      in: query
      description: Quantidade total de registros por páginas.
      schema:
        type: integer
        default: 25
        minimum: 1
